defaults:
  - base: default
  - augmentations: symmetric_96
  - wandb: "off"
  - override hydra/hydra_logging: "disabled"
  - override hydra/job_logging: "disabled"
  - _self_

name: "simclr-miniimagenet"
method: "simclr"
backbone:
  name: "resnet18"

method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 128
  temperature: 0.1

optimizer:
  name: "lars"
  batch_size: 128
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1.0e-6
  kwargs:
    clip_lr: true
    eta: 0.02
    exclude_bias_n_norm: true

scheduler:
  name: "warmup_cosine"
  warmup_epochs: 10
  max_epochs: 200

