defaults:
  - base: default
  - augmentations: symmetric_84
  - wandb: off
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

name: "simclr-miniimagenet"
method: "simclr"
backbone:
  name: "resnet18"

method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 512
  temperature: 0.2

optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1.0e-4
  kwargs:
    clip_lr: true
    eta: 0.02
    exclude_bias_n_norm: true

scheduler:
  name: "warmup_cosine"
  warmup_epochs: 10
  max_epochs: 200

