defaults:
  - base: default
  - augmentations: swav_multicrop_96
  - wandb: "off"
  - override hydra/hydra_logging: "disabled"
  - override hydra/job_logging: "disabled"
  - _self_

name: "swav-miniimagenet"
method: "swav"
backbone:
  name: "resnet18"

method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 128
  num_prototypes: 512
  queue_size: 4096
  epoch_queue_starts: 15
  freeze_prototypes_epochs: 2
  temperature: 0.1

optimizer:
  name: "lars"
  batch_size: 128
  lr: 0.6
  classifier_lr: 0.1
  weight_decay: 1.0e-6
  kwargs:
    clip_lr: true
    eta: 0.02
    exclude_bias_n_norm: true

scheduler:
  name: "warmup_cosine"
  warmup_epochs: 10
  max_epochs: 200

