defaults:
  - base: default
  - augmentations: symmetric_84
  - wandb: off
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

name: "vicreg-miniimagenet"
method: "vicreg"
backbone:
  name: "resnet18"

method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  sim_loss_weight: 25.0
  var_loss_weight: 25.0
  cov_loss_weight: 1.0

optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1.0e-4
  kwargs:
    clip_lr: true
    eta: 0.02
    exclude_bias_n_norm: true

scheduler:
  name: "warmup_cosine"
  warmup_epochs: 10
  max_epochs: 200

