defaults:
  - base: default
  - augmentations: symmetric_96
  - wandb: "off"
  - override hydra/hydra_logging: "disabled"
  - override hydra/job_logging: "disabled"
  - _self_

name: "vicreg-miniimagenet"
method: "vicreg"
backbone:
  name: "resnet18"

method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 4096
  sim_loss_weight: 25.0
  var_loss_weight: 25.0
  cov_loss_weight: 1.0

optimizer:
  name: "sgd"
  batch_size: 128
  lr: 0.2
  classifier_lr: 0.1
  weight_decay: 1.0e-4
  kwargs:
    momentum: 0.9

scheduler:
  name: "warmup_cosine"
  warmup_epochs: 10
  max_epochs: 200

